server:
  port: 9095

spring:
  application:
    name: spring-cloud-provider
  zipkin:
    base-url: http://123.58.4.18:9110/
  datasource:
    name: ytcnn
    #url: jdbc:mysql://localhost:3306/CRM?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/CRM?characterEncoding=utf-8
    username: root
    password: root
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://122.14.208.111:9091/eureka/,http://122.14.209.213:9091/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}:${eureka.instance.metadata-map.versions}
    metadata-map:
      versions: 3.0

serviceBamboo:
  multiVersion: crm:3.3.5,spring-cloud-consumer:1.0 #调用服务器的版本 用,间隔
  
ribbon:       
  MaxAutoRetriesNextServer: 2  ##重试服务的个数
  MaxAutoRetries: 0            ##访问当前服务的次数
  ConnectTimeout: 250
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true

#hystrix连接超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

mybatis:
  mapperLocations: classpath:mapper/*.xml  #指定*Mapper.xml的位置



#设置日志级别，打印mybatis的日志
logging:
  level:
    #root: debug
    root: info

feign:
  hystrix:
    enabled: true